// Package model contains the migrated domain entities for the original
// Spring/JPA application.
//
// This file migrates Cart.java. The original class was a JPA @Entity mapped to
// the "CART" table with an auto-generated integer primary key and a
// many-to-one association to a User (the customer), joined via the
// "customer_id" foreign-key column.
//
// MIGRATION_NOTE: Go has no ORM annotations or JPA. The idiomatic replacement is
// a plain struct that describes the row shape. Persistence concerns (table
// name, column names, foreign keys, ID generation) are handled explicitly by
// the repository/data-access layer using database/sql (or a lightweight helper)
// rather than by reflection-driven annotations.
//
//   - JPA @Id + @GeneratedValue(AUTO)  -> ID is populated by the database on
//     INSERT (e.g. AUTO_INCREMENT / SERIAL). The repository is responsible for
//     reading back the generated key.
//   - JPA @ManyToOne @JoinColumn(name="customer_id") -> the row physically
//     stores only the customer_id foreign key. We model both the raw key
//     (CustomerID) for persistence and an optional loaded association
//     (Customer) for convenience, mirroring how eager/lazy loading works.
package model

// Cart represents a row in the CART table: a shopping cart owned by a customer.
type Cart struct {
	// ID is the primary key. It is generated by the database on insert
	// (JPA @GeneratedValue(strategy = GenerationType.AUTO)).
	ID int

	// CustomerID is the "customer_id" foreign-key column referencing the owning
	// User. This is the value physically stored in the CART table.
	CustomerID int

	// Customer is the optionally-loaded owning User association
	// (JPA @ManyToOne @JoinColumn(name = "customer_id")).
	//
	// MIGRATION_NOTE: In JPA this association was navigable directly. In Go we
	// leave it nil unless the repository explicitly loads/joins it, avoiding the
	// hidden lazy-loading queries JPA would issue. Callers should check for nil
	// before dereferencing.
	Customer *User
}

// NewCart constructs a Cart for the given customer. The ID is left zero and is
// expected to be assigned by the database on insert.
//
// MIGRATION_NOTE: This replaces the JavaBean no-arg constructor plus setters.
// If User is not yet migrated, adjust the parameter/field types to match the
// eventual model.User definition.
func NewCart(customer *User) *Cart {
	c := &Cart{Customer: customer}
	if customer != nil {
		c.CustomerID = customer.ID
	}
	return c
}
